### ISSUE TITLE
i18n for text

### ISSUE THREAD

**Issue by kirsching** [jasonlewis/expressive-date#7] opened 2013-03-07 14:17 UTC
I would like to use your php extension. I would like to translate (getRelativeDate() / $units prefix, postfix etc.). Can you solve this problem? For example if the extension use language file.. then I be able to translate. Thanks for your support.

**Comment by jasonlewis** [comment] 2013-03-09 16:55
Duplicate of #3. I do plan on implementing some form of i18n. Thanks.

**Closed as completed by jasonlewis** 2013-03-09 16:55 UTC
